/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/images` | `/images`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/pricing` | `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/privacy` | `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/images` | `/images`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/pricing` | `/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/privacy` | `/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/terms` | `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/signin${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/camera${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/images${`?${string}` | `#${string}` | ''}` | `/images${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/pricing${`?${string}` | `#${string}` | ''}` | `/pricing${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/privacy${`?${string}` | `#${string}` | ''}` | `/privacy${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/support${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/terms${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/wardrobe${`?${string}` | `#${string}` | ''}` | `/wardrobe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/images` | `/images`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/pricing` | `/pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/privacy` | `/privacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/terms` | `/terms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownInputParams; };
    }
  }
}
